### PR TITLE
Chore: remove .DS_Store from repository

### PR DESCRIPTION
**Pull request by julienbeauchant**
Hello, i removed the .DS_store file. as you requested

### CODE REVIEW

**Comment by UnknOownU** [comment]
.DS_store file still in docs

**Review by UnknOownU — CHANGES_REQUESTED** [review]
delete .ds_store

**Review by UnknOownU — APPROVED** [review]
As requested you removed the .DS_file.

Its Okay for me to merge now.

**Review by Martial59110 — APPROVED** [review]
It's ok

**Pull request merged**
